<?php
/**
 * SOC Reporting System - PDF Export
 * Uses TCPDF to generate report PDFs.
 */

Session::requireLogin();

$machineSlot = (int) get('machine', 0);
$reportId = (int) get('id', 0);

if ($machineSlot < 1 || $machineSlot > MACHINE_SLOTS || $reportId < 1) {
    die('Invalid parameters');
}

$machine = getMachineBySlot($machineSlot);
if (!$machine) {
    die('Machine not found');
}

try {
    $db = Database::machine($machineSlot);
    $report = Database::fetchOne($db, "SELECT * FROM reports WHERE id = ?", [$reportId]);

    if (!$report) {
        die('Report not found');
    }

    $reportData = Database::fetchAll($db,
        "SELECT * FROM report_data WHERE report_id = ? ORDER BY id",
        [$reportId]
    );

    $formFields = getFormFields($machine['id']);
    $fieldMap = [];
    foreach ($formFields as $f) {
        $fieldMap[$f['id']] = $f;
    }

} catch (Exception $e) {
    die('Error: ' . $e->getMessage());
}

// Check if TCPDF is available
$tcpdfPath = APP_ROOT . '/assets/vendor/tcpdf/tcpdf.php';
if (file_exists($tcpdfPath)) {
    require_once $tcpdfPath;

    // Create PDF with TCPDF
    $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
    $pdf->SetCreator(APP_NAME);
    $pdf->SetAuthor($report['username']);
    $pdf->SetTitle('Report ' . $report['event_id']);

    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);
    $pdf->SetMargins(20, 20, 20);
    $pdf->AddPage();

    // Header
    $pdf->SetFont('helvetica', 'B', 20);
    $pdf->SetTextColor(0, 90, 120);
    $pdf->Cell(0, 12, APP_NAME, 0, 1, 'L');

    $pdf->SetFont('helvetica', '', 10);
    $pdf->SetTextColor(100, 100, 100);
    $pdf->Cell(0, 6, $machine['name'] . ' - Report', 0, 1, 'L');
    $pdf->Ln(6);

    // Divider
    $pdf->SetDrawColor(0, 180, 220);
    $pdf->SetLineWidth(0.5);
    $pdf->Line(20, $pdf->GetY(), 190, $pdf->GetY());
    $pdf->Ln(8);

    // Meta info
    $pdf->SetFont('helvetica', 'B', 9);
    $pdf->SetTextColor(80, 80, 80);

    $metaFields = [
        label('Event ID', 'Ereignis-ID') => $report['event_id'],
        label('Timestamp', 'Zeitstempel') => formatDatetime($report['created_at']),
        label('Created By', 'Erstellt von') => $report['username'],
        label('Status', 'Status') => ucfirst($report['status']),
    ];

    foreach ($metaFields as $metaLabel => $metaValue) {
        $pdf->SetFont('helvetica', 'B', 9);
        $pdf->SetTextColor(80, 80, 80);
        $pdf->Cell(40, 7, $metaLabel . ':', 0, 0, 'L');
        $pdf->SetFont('helvetica', '', 9);
        $pdf->SetTextColor(30, 30, 30);
        $pdf->Cell(0, 7, $metaValue, 0, 1, 'L');
    }

    $pdf->Ln(6);
    $pdf->Line(20, $pdf->GetY(), 190, $pdf->GetY());
    $pdf->Ln(8);

    // Report fields
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetTextColor(0, 90, 120);
    $pdf->Cell(0, 8, label('Report Data', 'Berichtsdaten'), 0, 1, 'L');
    $pdf->Ln(4);

    foreach ($reportData as $data) {
        $fieldDef = $fieldMap[$data['field_id']] ?? null;
        $fieldLabelText = $fieldDef ? fieldLabel($fieldDef) : $data['field_name'];

        $pdf->SetFont('helvetica', 'B', 9);
        $pdf->SetTextColor(80, 80, 80);
        $pdf->Cell(0, 6, strtoupper($fieldLabelText), 0, 1, 'L');

        $pdf->SetFont('helvetica', '', 10);
        $pdf->SetTextColor(30, 30, 30);
        $pdf->MultiCell(0, 6, $data['field_value'] ?: '--', 0, 'L');
        $pdf->Ln(4);
    }

    // Notes
    if ($report['notes']) {
        $pdf->Ln(4);
        $pdf->SetFont('helvetica', 'B', 9);
        $pdf->SetTextColor(80, 80, 80);
        $pdf->Cell(0, 6, strtoupper(label('Additional Notes', 'Zusätzliche Anmerkungen')), 0, 1, 'L');
        $pdf->SetFont('helvetica', '', 10);
        $pdf->SetTextColor(30, 30, 30);
        $pdf->MultiCell(0, 6, $report['notes'], 0, 'L');
    }

    // Footer
    $pdf->Ln(12);
    $pdf->SetFont('helvetica', '', 7);
    $pdf->SetTextColor(150, 150, 150);
    $pdf->Cell(0, 5, 'Generated by ' . APP_NAME . ' on ' . date(DATETIME_FORMAT), 0, 1, 'C');

    auditLog('pdf_export', "Exported PDF for report " . $report['event_id']);

    $pdf->Output('Report_' . $report['event_id'] . '.pdf', 'D');
    exit;

} else {
    // Fallback: generate a simple HTML-based printable view
    auditLog('pdf_export_fallback', "HTML export for report " . $report['event_id']);

    header('Content-Type: text/html; charset=utf-8');
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Report <?= e($report['event_id']) ?></title>
        <style>
            body { font-family: Arial, sans-serif; color: #1a1a2e; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { color: #005a78; font-size: 22px; margin-bottom: 4px; }
            .subtitle { color: #666; font-size: 13px; margin-bottom: 20px; }
            .divider { border-top: 2px solid #00b4dc; margin: 16px 0; }
            .meta-row { display: flex; margin-bottom: 6px; font-size: 13px; }
            .meta-label { width: 140px; font-weight: bold; color: #555; }
            .meta-value { color: #1a1a2e; }
            .section-title { font-size: 15px; font-weight: bold; color: #005a78; margin: 24px 0 12px; }
            .field { margin-bottom: 16px; }
            .field-label { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #888; margin-bottom: 4px; }
            .field-value { font-size: 14px; color: #1a1a2e; white-space: pre-wrap; }
            .footer { margin-top: 40px; font-size: 10px; color: #aaa; text-align: center; }
            @media print {
                body { padding: 20px; }
                .no-print { display: none; }
            }
        </style>
    </head>
    <body>
        <div class="no-print" style="margin-bottom: 20px;">
            <button onclick="window.print()" style="padding: 10px 20px; background: #005a78; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 14px;">
                <?= label('Print / Save as PDF', 'Drucken / Als PDF speichern') ?>
            </button>
            <button onclick="window.close()" style="padding: 10px 20px; background: #eee; color: #333; border: none; border-radius: 4px; cursor: pointer; font-size: 14px; margin-left: 8px;">
                <?= label('Close', 'Schließen') ?>
            </button>
        </div>

        <h1><?= e(APP_NAME) ?></h1>
        <div class="subtitle"><?= e($machine['name']) ?> - Report</div>
        <div class="divider"></div>

        <div class="meta-row"><div class="meta-label"><?= label('Event ID', 'Ereignis-ID') ?>:</div><div class="meta-value"><?= e($report['event_id']) ?></div></div>
        <div class="meta-row"><div class="meta-label"><?= label('Timestamp', 'Zeitstempel') ?>:</div><div class="meta-value"><?= formatDatetime($report['created_at']) ?></div></div>
        <div class="meta-row"><div class="meta-label"><?= label('Created By', 'Erstellt von') ?>:</div><div class="meta-value"><?= e($report['username']) ?></div></div>
        <div class="meta-row"><div class="meta-label"><?= label('Status', 'Status') ?>:</div><div class="meta-value"><?= e(ucfirst($report['status'])) ?></div></div>

        <div class="divider"></div>
        <div class="section-title"><?= label('Report Data', 'Berichtsdaten') ?></div>

        <?php foreach ($reportData as $data):
            $fieldDef = $fieldMap[$data['field_id']] ?? null;
            $fieldLabelText = $fieldDef ? fieldLabel($fieldDef) : $data['field_name'];
        ?>
        <div class="field">
            <div class="field-label"><?= e($fieldLabelText) ?></div>
            <div class="field-value"><?= e($data['field_value'] ?: '--') ?></div>
        </div>
        <?php endforeach; ?>

        <?php if ($report['notes']): ?>
        <div class="field">
            <div class="field-label"><?= label('Additional Notes', 'Zusätzliche Anmerkungen') ?></div>
            <div class="field-value"><?= e($report['notes']) ?></div>
        </div>
        <?php endif; ?>

        <div class="footer">Generated by <?= e(APP_NAME) ?> on <?= date(DATETIME_FORMAT) ?></div>
    </body>
    </html>
    <?php
    exit;
}
